#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/Client_ASK_42128.jar:$APPDIR/lib/core.jar:$APPDIR/lib/eeml.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/controlP5.jar" Client_ASK_42128
